all:
	g++ -std=c++11 -g -pthread quicksort.cpp MySort.cpp minheap.cpp -o fin.out

static:
	g++ -std=c++11 -g -pthread quicksort.cpp StaticMySort.cpp minheap.cpp -o finstat.out

chars:
	g++ -std=c++11 -g -pthread quicksort.cpp CharMySort.cpp minheap.cpp -o chars.out

final:
	g++ -std=c++11 -g -pthread quicksort.cpp FinalMySort.cpp minheap.cpp -o final.out